name: '.NET Build & Test'
description: 'Builds a .NET project, runs tests with code coverage, generates coverage report, and uploads build artifacts.'

inputs:
  dotnet-version:
    description: '.NET SDK version to install (e.g., 10.0.x).'
    required: false
    default: '10.0.x'
  project-path:
    description: 'Path to the solution or project file to build (e.g., src/MyApp.sln).'
    required: true
  test-path:
    description: 'Path to the test project. Leave empty to skip tests.'
    required: false
    default: ''
  configuration:
    description: 'Build configuration (Debug or Release).'
    required: false
    default: 'Release'
  publish-artifacts:
    description: 'Whether to publish build artifacts.'
    required: false
    default: 'true'
  artifact-name:
    description: 'Name for the uploaded build artifact.'
    required: false
    default: 'build-output'

runs:
  using: 'composite'
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      shell: bash
      run: dotnet restore "${{ inputs.project-path }}"

    - name: Build
      shell: bash
      run: dotnet build "${{ inputs.project-path }}" --configuration ${{ inputs.configuration }} --no-restore

    - name: Test
      if: inputs.test-path != ''
      shell: bash
      run: |
        dotnet test "${{ inputs.test-path }}" \
          --configuration ${{ inputs.configuration }} \
          --no-build \
          --logger "trx;LogFileName=test-results.trx" \
          --collect:"XPlat Code Coverage" \
          --results-directory ./test-results

    - name: Generate coverage report
      if: inputs.test-path != '' && always()
      shell: bash
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool 2>/dev/null || true
        COVERAGE_FILE=$(find ./test-results -name "coverage.cobertura.xml" -type f | head -1)
        if [ -n "$COVERAGE_FILE" ]; then
          reportgenerator \
            -reports:"$COVERAGE_FILE" \
            -targetdir:./test-results/coverage-report \
            -reporttypes:"HtmlInline_AzurePipelines;Cobertura"
          echo "Coverage report generated."
        else
          echo "No coverage file found, skipping report generation."
        fi

    - name: Upload test results
      if: inputs.test-path != '' && always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./test-results/
        retention-days: 30

    - name: Publish
      if: inputs.publish-artifacts == 'true'
      shell: bash
      run: |
        dotnet publish "${{ inputs.project-path }}" \
          --configuration ${{ inputs.configuration }} \
          --no-build \
          --output ./publish

    - name: Upload build artifact
      if: inputs.publish-artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ./publish/
        retention-days: 5
