name: 'Azure Login'
description: 'Authenticates to Azure using OIDC (preferred) or Service Principal fallback. Auto-detects mode based on whether client-secret is provided.'

inputs:
  client-id:
    description: 'Azure AD application (client) ID.'
    required: true
  tenant-id:
    description: 'Azure AD tenant ID.'
    required: true
  subscription-id:
    description: 'Azure subscription ID.'
    required: true
  client-secret:
    description: 'Service Principal client secret. Leave empty to use OIDC (recommended). When using OIDC, the calling workflow must set permissions: id-token: write.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Azure Login (OIDC)
      if: inputs.client-secret == ''
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}

    - name: Azure Login (Service Principal)
      if: inputs.client-secret != ''
      uses: azure/login@v2
      with:
        creds: |
          {
            "clientId": "${{ inputs.client-id }}",
            "clientSecret": "${{ inputs.client-secret }}",
            "tenantId": "${{ inputs.tenant-id }}",
            "subscriptionId": "${{ inputs.subscription-id }}"
          }

    - name: Verify login
      shell: bash
      run: |
        echo "::group::Azure account info"
        az account show --output table
        echo "::endgroup::"
