name: 'Helm Deploy to AKS'
description: 'Deploys an application to Azure Kubernetes Service using Helm. Supports default or custom charts, value file substitution, and env-values processing.'

inputs:
  aks-cluster-name:
    description: 'AKS cluster name.'
    required: true
  aks-resource-group:
    description: 'Azure resource group containing the AKS cluster.'
    required: true
  namespace:
    description: 'Kubernetes namespace for the deployment.'
    required: true
  release-name:
    description: 'Helm release name.'
    required: true
  chart-path:
    description: 'Path to a custom Helm chart. Leave empty to use the default chart from nuvtools-pipelines.'
    required: false
    default: ''
  values-file:
    description: 'Path to the Helm values file.'
    required: true
  env-values-file:
    description: 'Path to an env-values YAML file. Each key-value pair is passed as --set env.<key>=<value> to Helm.'
    required: false
    default: ''
  image-uri:
    description: 'Full container image URI (registry/name:tag). Replaces <IMAGE_PATH> in values file.'
    required: true
  app-version:
    description: 'Application version. Replaces <APP_VERSION> and <APP_NAME> placeholders in Chart.yaml.'
    required: true
  helm-timeout:
    description: 'Helm upgrade timeout.'
    required: false
    default: '5m0s'
  additional-set-values:
    description: 'Additional --set arguments for Helm (comma-separated key=value pairs).'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Get AKS credentials
      shell: bash
      run: |
        az aks get-credentials \
          --resource-group "${{ inputs.aks-resource-group }}" \
          --name "${{ inputs.aks-cluster-name }}" \
          --overwrite-existing

    - name: Prepare chart
      id: chart
      shell: bash
      run: |
        WORK_DIR="$(mktemp -d)"

        if [ -n "${{ inputs.chart-path }}" ]; then
          echo "Using custom chart: ${{ inputs.chart-path }}"
          cp -r "${{ inputs.chart-path }}/." "$WORK_DIR/"
        else
          echo "Using default nuvtools-pipelines chart"
          SCRIPT_DIR="${{ github.action_path }}"
          CHART_SRC="$SCRIPT_DIR/../../../charts/default"
          cp -r "$CHART_SRC/." "$WORK_DIR/"
        fi

        # Substitute placeholders in Chart.yaml
        sed -i "s|<APP_NAME>|${{ inputs.release-name }}|g" "$WORK_DIR/Chart.yaml"
        sed -i "s|<APP_VERSION>|${{ inputs.app-version }}|g" "$WORK_DIR/Chart.yaml"

        echo "chart-dir=$WORK_DIR" >> "$GITHUB_OUTPUT"
        echo "::group::Chart.yaml"
        cat "$WORK_DIR/Chart.yaml"
        echo "::endgroup::"

    - name: Prepare values
      id: values
      shell: bash
      run: |
        VALUES_WORK="$(mktemp)"
        cp "${{ inputs.values-file }}" "$VALUES_WORK"

        # Substitute <IMAGE_PATH> with the full image URI (without tag, as tag comes from Chart.appVersion)
        IMAGE_REPO=$(echo "${{ inputs.image-uri }}" | sed 's|:[^:]*$||')
        sed -i "s|<IMAGE_PATH>|${IMAGE_REPO}|g" "$VALUES_WORK"

        echo "values-path=$VALUES_WORK" >> "$GITHUB_OUTPUT"
        echo "::group::Values file"
        cat "$VALUES_WORK"
        echo "::endgroup::"

    - name: Process env-values
      id: env-values
      shell: bash
      run: |
        SET_ARGS=""
        if [ -n "${{ inputs.env-values-file }}" ] && [ -f "${{ inputs.env-values-file }}" ]; then
          echo "::group::Processing env-values file"
          # Lê cada par chave:valor do YAML e converte em argumentos --set
          while IFS=': ' read -r key value; do
            # Ignora linhas vazias e comentários
            [[ -z "$key" || "$key" == \#* ]] && continue
            # Remove aspas do valor
            value=$(echo "$value" | sed 's/^["'\'']*//;s/["'\'']*$//')
            if [ -n "$SET_ARGS" ]; then
              SET_ARGS="${SET_ARGS},env.${key}=${value}"
            else
              SET_ARGS="env.${key}=${value}"
            fi
            echo "  env.${key}=***"
          done < "${{ inputs.env-values-file }}"
          echo "::endgroup::"
        fi
        echo "args=$SET_ARGS" >> "$GITHUB_OUTPUT"

    - name: Helm upgrade
      shell: bash
      run: |
        SET_CMD=""

        # Argumentos de env-values
        ENV_ARGS="${{ steps.env-values.outputs.args }}"
        if [ -n "$ENV_ARGS" ]; then
          SET_CMD="--set $ENV_ARGS"
        fi

        # Argumentos adicionais
        EXTRA="${{ inputs.additional-set-values }}"
        if [ -n "$EXTRA" ]; then
          if [ -n "$SET_CMD" ]; then
            SET_CMD="$SET_CMD --set $EXTRA"
          else
            SET_CMD="--set $EXTRA"
          fi
        fi

        echo "::group::Helm upgrade"
        helm upgrade --install "${{ inputs.release-name }}" \
          "${{ steps.chart.outputs.chart-dir }}" \
          --namespace "${{ inputs.namespace }}" \
          --create-namespace \
          --values "${{ steps.values.outputs.values-path }}" \
          --timeout "${{ inputs.helm-timeout }}" \
          --wait \
          $SET_CMD
        echo "::endgroup::"

    - name: Verify rollout
      shell: bash
      run: |
        echo "::group::Rollout status"
        kubectl rollout status deployment/"${{ inputs.release-name }}" \
          --namespace "${{ inputs.namespace }}" \
          --timeout=300s
        echo "::endgroup::"

        echo "### Deployment Summary" >> "$GITHUB_STEP_SUMMARY"
        echo "| Property | Value |" >> "$GITHUB_STEP_SUMMARY"
        echo "|---|---|" >> "$GITHUB_STEP_SUMMARY"
        echo "| Release | \`${{ inputs.release-name }}\` |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Namespace | \`${{ inputs.namespace }}\` |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Cluster | \`${{ inputs.aks-cluster-name }}\` |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Image | \`${{ inputs.image-uri }}\` |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Version | \`${{ inputs.app-version }}\` |" >> "$GITHUB_STEP_SUMMARY"
