ARG DOTNET_VERSION=10.0
FROM mcr.microsoft.com/dotnet/aspnet:${DOTNET_VERSION}
WORKDIR /app
COPY . ./
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ARG ENTRY_POINT_DLL=""
ENV APP_DLL=${ENTRY_POINT_DLL}
ENTRYPOINT ["sh", "-c", "dotnet $APP_DLL"]
